export { default as Hour24 } from './24-hours.svg';
export { default as RightArrowSVG } from './rightarrowSVG.svg';
export { default as LocationSVG } from './locationSVG.svg';
export { default as UserSVG } from './userSVG.svg';
export { default as LockSVG } from './lockSVG.svg';
export { default as PencilSVG } from './pencilSVG.svg';
export { default as DescSVG } from './descSVG.svg';
export { default as RepeateSVG } from './repeteSVG.svg';
export { default as CategorySVG } from './categorySVG.svg';
